[general]
import = ["~/.config/alacritty/base.toml"]

[[hints.enabled]]
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
command = { program = "xdg-open" }
