[general]
import = ["~/AppData/Roaming/alacritty/base.toml"]
working_directory = "C:\\code"

[font]
normal = { family = "Inconsolata Nerd Font" }
size = 12

[terminal.shell]
program = "pwsh"

[[hints.enabled]]
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
command = { program = "cmd", args = ["/C", "start", ""] }
