[window]
blur = true
opacity = 0.9

[keyboard]
bindings = [
   { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[[hints.enabled]]
regex = "[^ ]+\\.(rs|java|xml|h|cpp|cc|kt|c|bp|mk|py|toml):\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }

[[hints.enabled]]
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+" 
command = { program = "xdg-open" }
mouse = { enabled = true }

[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"
